services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    network_mode: "host"

  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - APACHE_PORT=11000
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

  countryblock:
    # The block script will block any country
    # Requires cap_add as listed and privileged because it uses iptables and ipset
    image: alpine:latest
    restart: always
    container_name: countryblock
    volumes:
      - ./countryblock/block.sh:/block.sh:ro
      - ./data/countryblock-data:/data
      - ./data/countryblock-data/block.log:/var/log/block.log
      - ./logrotate/countryblock:/etc/logrotate.d/countryblock:ro
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file:
      - ./countryblock/countryblock.env
    command: >
      sh -c 'apk --update --no-cache add nftables wget bash tzdata &&
             sed -i "/bash \\/block\\.sh update/d" /etc/crontabs/root &&
             echo "$$COUNTRYBLOCK_SCHEDULE bash /block.sh update" >> /etc/crontabs/root &&
             crond -d 8 &&
             bash /block.sh start'

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
